services:
  bot:
    build: .
    container_name: star-voting-discord-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
